name: Flutter CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Flutter action
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.x'
          channel: 'stable'

      - name: Get dependencies
        run: flutter pub get

      - name: Analyze project
        run: dart analyze

      - name: Run tests
        run: flutter test

      # Build APKs for different architectures
      - name: Build APKs
        run: |
          flutter build apk --debug --target-platform android-arm,android-arm64,android-x64

      # Upload artifacts for each architecture
      - name: Upload APK (arm)
        uses: actions/upload-artifact@v3
        with:
          name: app-debug-arm
          path: build/app/outputs/flutter-apk/app-debug-armeabi-v7a.apk

      - name: Upload APK (arm64)
        uses: actions/upload-artifact@v3
        with:
          name: app-debug-arm64
          path: build/app/outputs/flutter-apk/app-debug-arm64-v8a.apk

      - name: Upload APK (x64)
        uses: actions/upload-artifact@v3
        with:
          name: app-debug-x64
          path: build/app/outputs/flutter-apk/app-debug-x86_64.apk